### ISSUE TITLE
Change model

### ISSUE THREAD

**Issue by sahil280114** [Clarifai/clarifai-android-starter#10]
How to change the general model to food items model cant do this?

**Comment by eddiezane** [comment]
You should be able to swap it out [here](https://github.com/Clarifai/clarifai-android-starter/blob/6552b4626a93dc8f8168c041ecf28a1b6118932e/app/src/main/java/com/clarifai/android/starter/api/v2/activity/RecognizeConceptsActivity.java#L94) for [`foodModel()`](https://github.com/Clarifai/clarifai-java/blob/6dfb1e12403c1f404e2796dc805319addb88101b/core/src/main/java/clarifai2/dto/model/DefaultModels.java#L104)
