### ISSUE TITLE
No connection to Clarifai and module cannot be loaded

### ISSUE THREAD

**Issue by EndyMsha** [Clarifai/clarifai-android-starter#15]
Hello,

I keep getting the failure "Error while contacting Clarifai API". 
Also it says sometimes during the start of Android Studio that the module "clarifai-android-starter-master.iml" cannot be loaded.

I installed the "Java SE Development Kit 8u161", changed the clarifai core number to 2.3.0 and pasted the API-number in strings.xml.

Any idea, why this should not work?

**Comment by mohammedjasam** [comment]
Hi @EndyMsha, 

Have you placed the API key in the string "clarifai_api_key"?

**Comment by EndyMsha** [comment]
Hi @mohammedjasam,

yes, I did replace the key.

**Comment by EndyMsha** [comment]
For the first test I replaced the API key with the number from the general model. This causes the error!
I replaced the API key with my own number and it works.
