### ISSUE TITLE
IllegalStateException - App has not been created yet!

### ISSUE THREAD

**Issue by Aaryanverma** [Clarifai/clarifai-android-starter#16]
I used this whole code and changed API key with mine but the app is crashing displaying the IllegalStateException("App has not been created yet!").  What should I change? Any possible solution?

**Comment by rok-povsic** [comment]
Hi @Aaryanverma ,

I've opened the project in Intellij Idea, marked "java" as source, installed Android SDK and some libraries which Intellij Idea automatically suggested, replaced `YOUR_API_KEY_HERE` and was able to run the project in an emulator. Are you sure you've set up the Android SDK and the other libraries correctly?

![image](https://user-images.githubusercontent.com/1495233/43730522-e2eb3112-99ab-11e8-913f-d3104728dbbd.png)

**Comment by Ehsan1997** [comment]
Ah you are too late, I fixed it but don't remember how.

بتاریخ سوموار، 6 اگست، 2018 10:10 بعد دوپہر rok-povsic <
notifications@github.com> نے لکھا:

**Comment by rok-povsic** [comment]
Good to hear that, good luck!

**Comment by Aaryanverma** [comment]
API key is correct, there is a runtime exception at async task, but I'm not getting the root cause of this error. help me with this.
  **logcat:** 
java.lang.RuntimeException: An error occurred while executing doInBackground()

**error in code at this line:** 

new AsyncTask<Void, Void, ClarifaiResponse<List<ClarifaiOutput<Concept>>>>() {
      @Override protected ClarifaiResponse<List<ClarifaiOutput<Concept>>> doInBackground(Void... params) {
        // The default Clarifai model that identifies concepts in images
        final ConceptModel foodModel = App.get().clarifaiClient().getDefaultModels().foodModel();

        // Use this model to predict, with the image that the user just selected as the input
        return foodModel.predict()
            .withInputs(ClarifaiInput.forImage(ClarifaiImage.of(imageBytes)))
            .executeSync();
      }
